development: &base
  adapter:  postgresql
  database: chicago_food_inspections
  encoding: utf8
  host: localhost
  min_messages: error
  password: <%= ENV['DATABASE_PASSWORD'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>

test: &test
  <<: *base
  database: chicago_food_inspections_test
